<a href="https://colab.research.google.com/github/AnvayM/Data-Science/blob/Santander_Customer_Satisfaction/Santander_Customer_Satisfaction_using_Varience_Thrashold_Feature_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split 
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
path="/content/drive/MyDrive/Colab Notebooks/Santander/train.csv"
santander=pd.read_csv(path,nrows=10000)

**The task is to predict the probability that each customer in the test set is an unsatisfied customer.**

In [ ]:
#VarienceThrashold removes the values having varience=0.
no_varience=VarianceThreshold(threshold=0)
no_varience.fit(x)

VarianceThreshold(threshold=0)

In [ ]:
x.columns[no_varience.get_support()]

Index(['A', 'B'], dtype='object')

In [ ]:
x.columns[no_varience.get_support(True)]

Index(['A', 'B'], dtype='object')

In [ ]:
y=no_varience.get_support()
y

array([ True,  True, False, False])

In [ ]:
# Printing those values which are not required.
rej_vals=[]
for i  in x:
  if i not in x.columns[no_varience.get_support()]:
    rej_vals.append(i)
print(rej_vals)

['C', 'D']

In [ ]:
#We are dropping the unwanted Columns.
X=x.drop(rej_vals,axis=1)
X

   A  B
0  1  4
1  2  5
2  3  6
3  4  7

In [ ]:
santander["TARGET"].sum()

388

In [ ]:
#VarianceThreshold will be applied on independent features only.
a=santander.drop("TARGET",axis=1)
b=santander["TARGET"]

In [ ]:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.3,random_state=50)
print(a_train.shape)
print(b_train.shape)
print(a_test.shape)
print(b_test.shape)

(7000, 370)
(7000,)
(3000, 370)
(3000,)

In [ ]:
th_col=VarianceThreshold(threshold=0)
th_col.fit(a_train)

VarianceThreshold(threshold=0)

In [ ]:

#gettig the columns which are having varience !=0
p=a_train.columns[th_col.get_support()]
p

Index(['ID', 'var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'],
      dtype='object', length=278)

In [ ]:
th_col.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True,  True,  True,  True, False, False, False, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False,  True, False,  True, False, False, False, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True, False,  True, False, False, False, False,  True,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
#number of columns having varience !=0
len(a_train.columns[th_col.get_support()])

278

In [ ]:
a_train.columns

Index(['ID', 'var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'],
      dtype='object', length=370)

In [ ]:
reject_cols=[columns for columns in a_train.columns
             if columns not in a_train.columns[th_col.get_support()]]
print(len(reject_cols))

92

In [ ]:
sum(th_col.get_support())

278

In [ ]:
a_train=a_train[p]

In [ ]:
a_train

         ID  var3  ...  saldo_medio_var44_ult3      var38
5189  10389     2  ...                     0.0   76521.39
7969  16063     2  ...                     0.0  461089.62
9039  18192     2  ...                     0.0  147307.50
5208  10433     2  ...                     0.0   34071.87
506    1019     2  ...                     0.0   30428.91
...     ...   ...  ...                     ...        ...
8262  16648     2  ...                     0.0  185106.21
6214  12489     2  ...                     0.0  129294.33
8324  16787     2  ...                     0.0   38921.19
6253  12569     2  ...                     0.0  144482.49
5600  11231     2  ...                     0.0   56942.91

[7000 rows x 278 columns]

In [ ]:
a_train

         ID  var3  ...  saldo_medio_var44_ult3      var38
5189  10389     2  ...                     0.0   76521.39
7969  16063     2  ...                     0.0  461089.62
9039  18192     2  ...                     0.0  147307.50
5208  10433     2  ...                     0.0   34071.87
506    1019     2  ...                     0.0   30428.91
...     ...   ...  ...                     ...        ...
8262  16648     2  ...                     0.0  185106.21
6214  12489     2  ...                     0.0  129294.33
8324  16787     2  ...                     0.0   38921.19
6253  12569     2  ...                     0.0  144482.49
5600  11231     2  ...                     0.0   56942.91

[7000 rows x 278 columns]

In [ ]:
a_test=a_test[p]
a_test

         ID  var3  ...  saldo_medio_var44_ult3          var38
9102  18315     2  ...                     0.0  405956.160000
7868  15844     2  ...                     0.0   48529.080000
4176   8390     2  ...                     0.0   46906.920000
4161   8358     2  ...                     0.0  126177.120000
8770  17658     2  ...                     0.0   54873.420000
...     ...   ...  ...                     ...            ...
6138  12342     2  ...                     0.0   85723.830000
6174  12413     2  ...                     0.0  114152.070000
3289   6604     2  ...                     0.0  117310.979016
5039  10062     2  ...                     0.0   75191.070000
3111   6262     2  ...                     0.0  104009.940000

[3000 rows x 278 columns]

In [ ]:
#Since the value  of traget variable is binary the we will do Logistics Regression.
lr=LogisticRegression()

In [ ]:
lr.fit(a_train,b_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lr.predict(a_test)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
accuracy=confusion_matrix(b_test,lr.predict(a_test))

In [ ]:
accuracy

array([[2869,    0],
       [ 131,    0]])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
q=accuracy_score(b_test,lr.predict(a_test))

In [ ]:
q

0.9563333333333334